[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "sonar2csv_shape"
dynamic = ["version"]
description = "Convert sl2 and sl3 files from sonar measurements to csv and shape"
readme = "README.md"
requires-python = ">=3.11"
license = {text = "GNU3"}
authors = [{name = "Hopsakee", email = "hopsakee@posteo.nl"}]
keywords = ['nbdev', 'jupyter', 'notebook', 'python']
classifiers = ["Natural Language :: English", "Intended Audience :: Developers", "Development Status :: 3 - Alpha", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3 :: Only"]
dependencies = []

[project.urls]
Repository = "https://github.com/Hopsakee/sonar2csv_shape"
Documentation = "https://Hopsakee.github.io/sonar2csv_shape"

[project.entry-points.nbdev]
sonar2csv_shape = "sonar2csv_shape._modidx:d"

[tool.setuptools.dynamic]
version = {attr = "sonar2csv_shape.__version__"}

[tool.setuptools.packages.find]
include = ["sonar2csv_shape"]

[tool.nbdev]
