# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/sonar2csv_shape',
                'doc_host': 'https://Hopsakee.github.io',
                'git_url': 'https://github.com/Hopsakee/sonar2csv_shape',
                'lib_path': 'sonar2csv_shape'},
  'syms': { 'sonar2csv_shape.cmdline': {'sonar2csv_shape.cmdline.main': ('cmdline.html#main', 'sonar2csv_shape/cmdline.py')},
            'sonar2csv_shape.convert': { 'sonar2csv_shape.convert.clean_gdf': ('convert.html#clean_gdf', 'sonar2csv_shape/convert.py'),
                                         'sonar2csv_shape.convert.export_gdf': ('convert.html#export_gdf', 'sonar2csv_shape/convert.py'),
                                         'sonar2csv_shape.convert.extract_height': ( 'convert.html#extract_height',
                                                                                     'sonar2csv_shape/convert.py'),
                                         'sonar2csv_shape.convert.process_sonar_file': ( 'convert.html#process_sonar_file',
                                                                                         'sonar2csv_shape/convert.py'),
                                         'sonar2csv_shape.convert.read_sl': ('convert.html#read_sl', 'sonar2csv_shape/convert.py'),
                                         'sonar2csv_shape.convert.slx2gdf': ('convert.html#slx2gdf', 'sonar2csv_shape/convert.py')},
            'sonar2csv_shape.web': {}}}
