# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/sonar2csv_shape',
                'doc_host': 'https://jelledejong@wdodelta.nl.github.io',
                'git_url': 'https://github.com/jelledejong@wdodelta.nl/sonar2csv_shape',
                'lib_path': 'sonar2csv_shape'},
  'syms': {'sonar2csv_shape.core': {'sonar2csv_shape.core.foo': ('core.html#foo', 'sonar2csv_shape/core.py')}}}
