"""Module making it possible to run the conversion from slX-files possible from the command line in bash"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_cmdline.ipynb.

# %% auto 0
__all__ = ['main']

# %% ../nbs/01_cmdline.ipynb 5
import argparse
from pathlib import Path
from .convert import *

# %% ../nbs/01_cmdline.ipynb 8
def main():
    parser = argparse.ArgumentParser(description="Convert sonar files (sl2/sl3) to CSV and shapefile")
    parser.add_argument('input', type=Path, help="Path to sl2 or sl3 file")
    parser.add_argument('output', type=Path, help="Output folder for exported files")
    parser.add_argument('--crs', default='epsg:28992', help="Target CRS (default: epsg:28992)")
    args = parser.parse_args()
    process_sonar_file(args.input, args.output, args.crs)
