"""Module that create the web application to make it possible to upload a slX-file and run the conversion from the slX-files to shape, csv and geopackage"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_web.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/02_web.ipynb 2
#| export
#| default_exp web

# %% ../nbs/02_web.ipynb 5
from fastcore.utils import *
from fasthtml.common import *
from fasthtml.jupyter import *
from fastlite import *
import fasthtml.components as fh
import httpx
from pathlib import Path

from .core import *
