"""Module making it possible to run the conversion from slX-files from a web interface"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_webgui.ipynb.

# %% auto 0
__all__ = ['theme_css', 'daisy_hdrs', 'app', 'rt', 'sonarhome', 'upload', 'get_file', 'cleanup', 'index', 'main']

# %% ../nbs/02_webgui.ipynb 4
import zipfile
from fastcore.utils import *
from fasthtml.common import *
from fasthtml.jupyter import *
from fastlite import *
import fasthtml.components as fh
import httpx
from pathlib import Path

from .convert import *

# %% ../nbs/02_webgui.ipynb 9
theme_css = """
[data-theme="WDODelta"] {
  --color-base-100: oklch(100% 0 0);
  --color-base-200: oklch(98% 0 0);
  --color-base-300: oklch(95% 0 0);
  --color-base-content: oklch(21% 0.006 285.885);
  --color-primary: #075895;
  --color-primary-content: oklch(93% 0.034 272.788);
  --color-secondary: #00b0ea;
  --color-secondary-content: oklch(94% 0.028 342.258);
  --color-accent: #93c01f;
  --color-accent-content: oklch(38% 0.063 188.416);
  --color-neutral: oklch(14% 0.005 285.823);
  --color-neutral-content: oklch(92% 0.004 286.32);
  --color-info: #00b0ea;
  --color-info-content: oklch(29% 0.066 243.157);
  --color-success: #93c01f;
  --color-success-content: oklch(37% 0.077 168.94);
  --color-warning: #f29100;
  --color-warning-content: oklch(41% 0.112 45.904);
  --color-error: #d74116;
  --color-error-content: oklch(27% 0.105 12.094);
  --rounded-box: 0.5rem;
  --rounded-btn: 2rem;
  --rounded-badge: 2rem;
  --btn-text-case: uppercase;
}
"""

# %% ../nbs/02_webgui.ipynb 10
daisy_hdrs = (
    Link(href='https://cdn.jsdelivr.net/npm/daisyui@5', rel='stylesheet', type='text/css'),
    Script(src='https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4'),
    Link(href='https://cdn.jsdelivr.net/npm/daisyui@5/themes.css', rel='stylesheet', type='text/css'),
    Style(theme_css),
)

# %% ../nbs/02_webgui.ipynb 11
app = FastHTML(hdrs=daisy_hdrs, htmlkw={'data-theme': 'WDODelta'})
rt = app.route

# %% ../nbs/02_webgui.ipynb 37
@rt
def sonarhome():
    return Div(
        Title("Sonar File Converter"),
        Div(cls="min-h-screen bg-cover bg-center",
            style="background-image: url('https://cuatro.sim-cdn.nl/wdodelta/uploads/styles/large_5x2_2560x1024/media/foto_-_stuw_en_duiker_bij_lambert_van_der_linde_albertzoon_weg_3_0.jpg?h=e600bad3&cb=Y-KMqDmb')"
            )(H1("Sonar File Converter", cls="text-4xl font-bold text-center p-8"),
            Article(cls="flex flex-col items-center justify-center ")(
                Form(hx_post=upload, hx_target="#result", hx_indicator="#spinner", hx_disabled_elt="button", cls="flex gap-2")(
                    Input(type="file", name="file", cls="file-input file-input-bordered"),
                    Button("Upload and Convert", type="submit", cls='btn btn-primary'),
                    Span(cls="loading loading-spinner loading-lg htmx-indicator", id="spinner")
                ),
                Div(id="result")
            )
        )
    )


# %% ../nbs/02_webgui.ipynb 39
@rt
async def upload(file: UploadFile):
    upload_dir = Path("/app/data")
    filebuffer = await file.read()
    print(file.filename)
    input_path = upload_dir / file.filename
    input_path.write_bytes(filebuffer)
    
    process_sonar_file(input_path, upload_dir)
    
    stem = Path(input_path).stem
    zip_path = upload_dir / f"{stem}.zip"
    with zipfile.ZipFile(zip_path, 'w') as zf:
        for ext in ['.shp', '.shx', '.dbf', '.prj', '.cpg', '.csv', '.gpkg']:
            fp = upload_dir / f"{stem}{ext}"
            if fp.exists(): zf.write(fp, fp.name); fp.unlink()
    
    input_path.unlink()
    
    return Div(
        P(f"Conversion complete!"),
        A("Download Results", href=get_file.to(fn=zip_path.name), cls='btn btn-success', 
          hx_on__after_request=f"fetch('/cleanup?fn={zip_path.name}', {{method: 'POST'}})")
    )

# %% ../nbs/02_webgui.ipynb 41
@rt
def get_file(fn: str):
    upload_dir = Path("/app/data")
    filepath = upload_dir/fn
    return FileResponse(filepath, filename=fn)

# %% ../nbs/02_webgui.ipynb 43
@rt
def cleanup(fn: str): 
    upload_dir = Path("/app/data")
    fp = upload_dir / fn
    if fp.exists(): fp.unlink()

# %% ../nbs/02_webgui.ipynb 47
@rt
def index(): return RedirectResponse('/sonarhome')

# %% ../nbs/02_webgui.ipynb 49
def main():
    """Start the web server locally for the sonar file converter"""
    serve()
