"""Module making it possible to run the conversion from slX-files from a web interface"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_webgui.ipynb.

# %% auto 0
__all__ = ['theme_css', 'daisy_hdrs', 'app', 'rt', 'srv', 'sonarhome', 'upload', 'cleanup']

# %% ../nbs/02_webgui.ipynb 4
import zipfile
from fastcore.utils import *
from fasthtml.common import *
from fasthtml.jupyter import *
from fastlite import *
import fasthtml.components as fh
import httpx
from pathlib import Path

from .convert import *

# %% ../nbs/02_webgui.ipynb 8
theme_css = """
[data-theme="WDODelta"] {
  --color-base-100: oklch(100% 0 0);
  --color-base-200: oklch(98% 0 0);
  --color-base-300: oklch(95% 0 0);
  --color-base-content: oklch(21% 0.006 285.885);
  --color-primary: #075895;
  --color-primary-content: oklch(93% 0.034 272.788);
  --color-secondary: #00b0ea;
  --color-secondary-content: oklch(94% 0.028 342.258);
  --color-accent: #93c01f;
  --color-accent-content: oklch(38% 0.063 188.416);
  --color-neutral: oklch(14% 0.005 285.823);
  --color-neutral-content: oklch(92% 0.004 286.32);
  --color-info: #00b0ea;
  --color-info-content: oklch(29% 0.066 243.157);
  --color-success: #93c01f;
  --color-success-content: oklch(37% 0.077 168.94);
  --color-warning: #f29100;
  --color-warning-content: oklch(41% 0.112 45.904);
  --color-error: #d74116;
  --color-error-content: oklch(27% 0.105 12.094);
  --rounded-box: 0.5rem;
  --rounded-btn: 2rem;
  --rounded-badge: 2rem;
  --btn-text-case: uppercase;
}
"""

# %% ../nbs/02_webgui.ipynb 9
daisy_hdrs = (
    Link(href='https://cdn.jsdelivr.net/npm/daisyui@5', rel='stylesheet', type='text/css'),
    Script(src='https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4'),
    Link(href='https://cdn.jsdelivr.net/npm/daisyui@5/themes.css', rel='stylesheet', type='text/css'),
    Style(theme_css),
)

# %% ../nbs/02_webgui.ipynb 10
app = FastHTML(hdrs=daisy_hdrs, htmlkw={'data-theme': 'WDODelta'})
rt = app.route

# %% ../nbs/02_webgui.ipynb 14
srv = JupyUvi(app=app)

# %% ../nbs/02_webgui.ipynb 31
@rt
def sonarhome():
    return Titled("Sonar File Converter",
        Article(
            Form(hx_post=upload, hx_target="#result")(
                Input(type="file", name="file", cls="file-input file-input-bordered"),
                Button("Upload and Convert", type="submit", cls='btn btn-primary'),
            ),
            Div(id="result")
        )
    )

@rt
async def upload(file: UploadFile):
    upload_dir = Path("/app/data")
    filebuffer = await file.read()
    input_path = upload_dir / file.filename
    input_path.write_bytes(filebuffer)
    
    process_sonar_file(str(input_path), str(upload_dir))
    
    stem = Path(input_path).stem
    zip_path = upload_dir / f"{stem}.zip"
    with zipfile.ZipFile(zip_path, 'w') as zf:
        for ext in ['.shp', '.shx', '.dbf', '.prj', '.csv', '.gpkg']:
            fp = upload_dir / f"{stem}{ext}"
            if fp.exists(): zf.write(fp, fp.name); fp.unlink()
    
    input_path.unlink()
    
    return Div(
        P(f"Conversion complete!"),
        A("Download Results", href=get_file.to(fn=zip_path.name), cls='btn btn-success', 
          hx_on__after_request=f"fetch('/cleanup?fn={zip_path.name}', {{method: 'POST'}})")
    )

@rt
def cleanup(fn: str): 
    upload_dir = Path("/app/data")
    fp = upload_dir / fn
    if fp.exists(): fp.unlink()
