# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/sonar2csv_shape',
                'doc_host': 'https://Hopsakee.github.io',
                'git_url': 'https://github.com/Hopsakee/sonar2csv_shape',
                'lib_path': 'src'},
  'syms': { 'src.core': { 'src.core.clean_gdf': ('core.html#clean_gdf', 'src/core.py'),
                          'src.core.export_gdf': ('core.html#export_gdf', 'src/core.py'),
                          'src.core.extract_height': ('core.html#extract_height', 'src/core.py'),
                          'src.core.process_sonar_file': ('core.html#process_sonar_file', 'src/core.py'),
                          'src.core.read_sl': ('core.html#read_sl', 'src/core.py'),
                          'src.core.slx2gdf': ('core.html#slx2gdf', 'src/core.py')}}}
