# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/sonar2csv_shape',
                'doc_host': 'https://Hopsakee.github.io',
                'git_url': 'https://github.com/Hopsakee/sonar2csv_shape',
                'lib_path': 'src'},
  'syms': { 'src.core': { 'src.core.extract_height': ('core.html#extract_height', 'src/core.py'),
                          'src.core.read_sl': ('core.html#read_sl', 'src/core.py'),
                          'src.core.sl2gdf': ('core.html#sl2gdf', 'src/core.py')}}}
