# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/sonar2csv_shape',
                'doc_host': 'https://Hopsakee.github.io',
                'git_url': 'https://github.com/Hopsakee/sonar2csv_shape',
                'lib_path': 'src'},
  'syms': {'src.core': {'src.core.foo': ('core.html#foo', 'src/core.py')}}}
