"""Module containing the reading and conversion logic from the sl2 and sl3 files to csv and shape"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['read_sl', 'extract_height', 'sl2gdf', 'depth2height']

# %% ../nbs/00_core.ipynb 5
import geopandas as gpd
from pathlib import Path
from sonarlight import Sonar

# %% ../nbs/00_core.ipynb 9
def read_sl(
    filepath: Path # The absolute location of the file to convert
    )->Sonar:
    return Sonar(str(filepath))

# %% ../nbs/00_core.ipynb 31
def extract_height(
    sl_filepath: Path, # The absolute location of the file to convert
    re_ptrn: str=r"[+-]\d+(?=cmnap)"
    )->int: # The height of the measurement station in cm above NAP
    "Extract height from the filename in cmNAP"
    if 'cmnap' not in str(sl_filepath).lower():
        raise ValueError("The filename must contain the height of the Sonar boot at time of measurement in 'cmNAP' at the end of the filename (e.g. 'example_description_+1050cmNAP.sl2')")
    return int(re.search(re_ptrn, str(sl2file), flags=re.IGNORECASE[0]))

# %% ../nbs/00_core.ipynb 32
def sl2gdf(
    sl_filepath: Path, # The absolute location of the file to convert
    msrmnt_height: int, # Height of the measurement instrument at time of taking the measurements
    to_crs: str = "epsg:28992", # epsg code of crs to transform the coördinates to
    survey_fltr: str = "primary", # Filter measurement facts on survey value
    )->gpd:
    "Convert a sl2 or sl3 file to a GeoDataFrame with the given crs."
    s = Sonar(str(sl_filepath))
    df = s.df
    gdf = gpd.GeoDataFrame(df, geometry=geopandas.points_from_xy(df.longitude, df.latitude))
    gdf = gdf.set_crs(epsg=4326)
    return gdf.to_crs(to_crs)

# %% ../nbs/00_core.ipynb 34
def depth2height(
    gdf: gpd, # GeoDataFrame from measurements with "water_depth" column in meter
    gps_altitude: int, # The height of the measurement instrument in cm NAP
    )->gpd: # GeoDataFrame with measurements in mNAP
    if "water_depth" in gdf.columns:
        raise KeyError("Column 'water_depth' not found in GeoDataFrame")
    pass

